---
title: "Aprendizado de Máquina"
subtitle: "Disciplina EST171 da pós-graduação em Estatística UFMG"
output: html_document
---

Página dedicada ao armazenamento e disponibilização dos materiais
elaborados na disciplina
[EST171 - Aprendizado de Máquina][est171],
ofertada pelo departamento de Estatística na Universidade Federal de
Minas Gerais como disciplina optativa do programa de Pós-Graduação,
ministrada pelo professor [Marcos Prates][marcosop].

Na disciplina temos como base o livro
[An Introduction to Statistical Learning][livro] dos autores James, G.,
Witten, D., Hastie, T. e Tibshirani, cujo tem soluções (não oficiais)
dos execícios disponibilizadas por [Amir Sadoughi][amir] em seu
[blog do GitHub][solutions].

As atividades complementares às aulas ministradas pelo docente são
divididas em listas de exercício, cujo soluções são armazenadas em
[`listas/`]; seminários (apresentando um artigo), cujo slides serão
armazenados em [`seminars/`]; e um trabalho prático elaborado com um
resumo expandido e apresentado em formato de pôster, os arquivos
referentes ao trabalho prático são armazenados no diretório
[`practical/`]. A lista de materiais elaborados é exibida abaixo:

* **Lista 1** ([PDF](./lista1.pdf) / [HTML](./lista1.html) com códigos) -
  Machine Learning em problemas de Regressão: aplicação de regressão sob
  penalização Lasso e KNN.\
* **Lista 2** ([PDF](./lista2.pdf) / [HTML](./lista2.html) com códigos) -
  Machine Learning em problemas de Classificação: aplicação das
  abordagens via regressão logística, gaussiana, naive bayes,
  discriminante linear, discriminante quadrático e KNN.\

Para sugestões, críticas ou relato de problemas abra uma _issue_ em
[htps://github.com/JrEduardo/est171-ml/issues](https://github.com/JrEduardo/est171-ml/issues)
ou entre em contato por e-mail [edujrrib@gmail.com](mailto:edujrrib@gmail.com)

## Licença ##

Este material é distribuído sob a licença
[GNU General Public License, versão 3], descrita no arquivo
[`LICENSE.md`], © 2016 E. E., Ribeiro Jr

[est171]: http://est.ufmg.br/~marcosop/est171-ML
[marcosop]: http://est.ufmg.br/~marcosop
[livro]: http://www.springer.com/us/book/9781461471370
[amir]: http://princehonest.com/
[solutions]: http://blog.princehonest.com/stat-learning/
[`listas/`]: https://github.com/JrEduardo/est171-ml/tree/master/listas
[`seminars/`]: https://github.com/JrEduardo/est171-ml/tree/master/seminars
[`practical/`]: https://github.com/JrEduardo/est171-ml/tree/master/practical
[GNU General Public License, versão 3]: https://www.gnu.org/licenses/gpl-3.0.html
[`LICENSE.md`]: https://github.com/JrEduardo/ce227-bayes/blob/master/LICENSE.md
